config/routes.rb
Rails.application.routes.draw do
  resources :parts
  devise_for :users, controllers: {registrations: "registrations"}
  resources :cars
  resources :tickets
  resources :events
  root "pages#home"
  get "/todo" => "pages#todo_index"
  get "filter" => "pages#filter"
  get "completed-tickets" => "tickets#completed"
  get "finalize" => "tickets#finalize_ticket"
  get "all" => "cars#all_cars"
  get "calendar" => "pages#calendar"
  get "admin" => "pages#admin"
  get "search" => "reports#set_filters"
end

app/models/part.rb
class Part < ApplicationRecord
  def self.search(search_term)
    where("LOWER(name) LIKE :search_term", search_term: "%#{search_term.downcase}%")
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    if params[:search]
      search_term = params[:search]
      @parts = Part.search(search_term)
    else
      @parts = Part.order(:name)
    end
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: "Part was successfully created." }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: "Part was successfully updated." }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: "Part was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_part
    @part = Part.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def part_params
    params.require(:part).permit(:name, :part_num, :quantity, :description)
  end
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/_form.html.erb
<div class="formContainer">
  <%= form_with(model: part, local: true) do |form| %>
    <% if part.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

        <ul>
        <% part.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="ticketItem">
      NAME
      <%= form.text_field :name %>
    </div>

    <div class="ticketItem">
      PART NUMBER
      <%= form.text_field :part_num %>
    </div>

    <div class="ticketItem">
      QUANTITY <br>
      <%= form.select(:quantity, (0..50).map {|i| [i,i]} ) %>
    </div>

    <div class="ticketItem">
      DESCRIPTION
      <%= form.text_field :description %>
    </div>

    <div class="doneButton">
      <%= form.submit "DONE", id: "done" %>
    </div>
  <% end %>
</div>

app/views/parts/edit.html.erb
<h1>Editing Part</h1>

<%= render 'form', part: @part %>

<%= link_to 'Show', @part %> |
<%= link_to 'Destroy', @part, method: :delete, data: { confirm: 'Are you sure? Deleting will completely remove this part.' } %> |
<%= link_to 'Back', parts_path %>

app/views/parts/index.html.erb
<%= render partial: 'layouts/navbar', locals: {title: "INVENTORY LIST"} %>

<h2 class="header"> INVENTORY LIST </h2>

<div id="newPartButton">
  <%= link_to 'CREATE NEW PART', new_part_path, {class: "newPart"} %>
</div>

<hr>

<h5 class="searchHeader"> SEARCH </h5>

<div class="searchBar">
  <%= form_for "", url: parts_path, method: :get do |f| %>
    <%= f.text_field :search, placeholder: "..."%>
  <% end %>
</div>

<hr>

<div class='priorityBox'>
    <div class='priorityBoxTitle'> INVENTORY </div>
    <% @parts.each do |part| %>
        <div class='priorityTickets'>
             <%= link_to part_path(:id => part.id) do %>
                <div class='partLink'>
                    <div class="leftPart"><%= part.name %></div>
                    <% if(part.quantity > 0)%>
                        <div class="rightPart"><%= part.quantity %> in stock</div>
                    <% else %>
                        <div class="rightPart"><span class="red">Out of stock</span></div>
                    <% end %>
                </div>
            <% end %>
        </div>
    <% end %>
</div>

app/views/parts/new.html.erb
<%= render partial: 'layouts/navbar', locals: {title: "INVENTORY LIST"} %>

<h3 class="header"> ADD NEW PART </h3>



<%= render 'form', part: @part %>

app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @part.name %>
</p>

<p>
  <strong>Part num:</strong>
  <%= @part.part_num %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @part.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @part.description %>
</p>

<%= link_to 'Edit', edit_part_path(@part) %> |
<%= link_to 'Back', parts_path %>