config/routes.rb
Rails.application.routes.draw do
  resources :parts
  devise_for :users, controllers: {registrations: "registrations"}
  resources :cars
  resources :tickets
  resources :events
  root "pages#home"
  get "/todo" => "pages#todo_index"
  get "filter" => "pages#filter"
  get "completed-tickets" => "tickets#completed"
  get "finalize" => "tickets#finalize_ticket"
  get "all" => "cars#all_cars"
  get "calendar" => "pages#calendar"
  get "admin" => "pages#admin"
  get "search" => "reports#set_filters"
end

app/views/pages/_todo.html.erb
<div class='highPriorityBox'>
    <div class='priorityBoxTitle'> HIGH PRIORITY </div>
        <% @high_priority_todo.each do |item| %>
        <div class='priorityTickets'>
             <% if(item.in_progress) == true %>
             <%= link_to finalize_path(:id => item.id) do %>
                <div class='ticketLink green'>
                    <div class="leftDiv"><%= item.car.name %></div>
                    <div class="centerDiv"><%= item.category %></div>
                    <div class="rightDiv"><%= item.car.generation %></div>
                </div>
                <% end %>
                <% elsif(item.repair_under_warranty == true) %>
             <%= link_to ticket_path(:id => item.id) do %>
                <div class='ticketLink yellow'>
                    <div class="leftDiv"><%= item.car.name %></div>
                    <div class="centerDiv"><%= item.category %></div>
                    <div class="rightDiv"><%= item.car.generation %></div>
                </div>
            <% end %>
                <% else %>
             <%= link_to ticket_path(:id => item.id) do %>
                <div class='ticketLink'>
                    <div class="leftDiv"><%= item.car.name %></div>
                    <div class="centerDiv"><%= item.category %></div>
                    <div class="rightDiv"><%= item.car.generation %></div>
                </div>
            <% end %>
            <% end %>
        </div>
    <% end %>

</div>


<div class='priorityBox'>
    <div class='priorityBoxTitle'> TO-DO LIST </div>
    <% @todo.each do |item| %>
        <div class='priorityTickets'>
             <% if(item.in_progress) == true %>
             <%= link_to finalize_path(:id => item.id) do %>
                <div class='ticketLink green'>
                    <div class="leftDiv"><%= item.car.name %></div>
                    <div class="centerDiv"><%= item.category %></div>
                    <div class="rightDiv"><%= item.car.generation %></div>
                </div>
                <% end %>
                <% else %>
             <%= link_to ticket_path(:id => item.id) do %>
                <div class='ticketLink'>
                    <div class="leftDiv"><%= item.car.name %></div>
                    <div class="centerDiv"><%= item.category %></div>
                    <div class="rightDiv"><%= item.car.generation %></div>
                </div>
            <% end %>
            <% end %>
        </div>
    <% end %>
</div>

app/views/pages/admin.html.erb
<div class="adminContainer">

    <span class='new-user-link'>
        <%= link_to 'Create new user', new_user_registration_path %> 
    </span>

    <span class='new-car-link'>
        <%= link_to 'Create new car', new_car_path %> 
    </span>

</div>

app/views/pages/calendar.html.erb
<%= render partial: 'layouts/navbar', locals: {title: "CALENDAR"} %>


<div class='calendar'></div> 

app/views/pages/home.html.erb
<%= render partial: 'layouts/navbar', locals: {title: "DASHBOARD"} %>


<div class="imgdiv">
    <img src="https://i.imgur.com/wqfPOwS.png" alt="Free Bee Logo">
</div>



<ul id="grid" class="clear">
        <li>
             <%= link_to cars_path do %>
                <div class="hexagon"> 
                <p class='hexText'> ADD ISSUE </p>
            <% end %>
            </div>
        </li>
        <li>
            <%= link_to todo_path do %>
                <div class="hexagon">
                <p class='hexText'> PRIORITY TO-DO LIST </p>
            </div>
            <% end %>
        </li>
        <li>
            <%= link_to completed_tickets_path do %>
                <div class="hexagon">
                <p class='hexText'> COMPLETED LOG </p>
                </div>
            <% end %>
        </li>
        <li>
            <%= link_to parts_path do %>
                <div class="hexagon">
                <p class='hexText'> INVENTORY LIST </p>
                </div>
            <% end %>
        </li>
        <li>
            <%= link_to calendar_path do %>
                <div class="hexagon">
                <p class='hexText'> CALENDAR </p>
                </div>
            <% end %>
        </li>
        <li>
            <%= link_to all_path do %>
                <div class="hexagon">
                <p class='hexText'> CARS </p>
                </div>
            <% end %>
        </li>
        <li>
            <%= link_to all_path do %>
                <div class="hexagon hide">
                <p class='hexText'> CARS </p>
                </div>
            <% end %>
        </li>
        <li><% if current_user.admin? %>
                <%= link_to admin_path do %>
                    <div class="hexagon ">
                    <p class='hexText'> ADMIN </p>
                    </div>
                <% end %>
            <% end %>
        </li>
        <li>
            <%= link_to search_path do %>
                <div class="hexagon">
                <p class='hexText'> REPORTS </p>
                </div>
            <% end %>
        </li>
</ul>

<div class='highPriorityBox homeBox'>
    <div class='priorityBoxTitle'> HIGH PRIORITY </div>
        <% @tickets.each do |ticket| %>
            <%= link_to ticket_path(ticket.id) do %>
                <div class='homePagePriority'>
                    <span class='ticketCarName'><%= ticket.car.name %></span> <br>
                    <span class='ticketCarCat'><%= ticket.category %></span>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/pages/todo_index.html.erb
<%= render partial: 'layouts/navbar', locals: {title: "PRIORITY TO-DO LIST"} %>


<%= form_for "", url: todo_path, method: :get do |f| %>
	<div id="filter-header"> ZONE </div>
	<div class="filter-style">
	<%= f.select :filter, ['All','Coconut Grove', 'Coral Gables', 'Hallandale Beach', 'Key Biscayne', 'Mainland', 'Miami Lakes', 'South Beach', 'Other'], {
		:include_blank => true, id: "filter" } , { onchange: 'this.form.submit();', prompt: 'Select Person' } %>
	</div>
<% end %>



<%= render 'pages/todo' %>