config/routes.rb
Rails.application.routes.draw do
  resources :parts
  devise_for :users, controllers: {registrations: "registrations"}
  resources :cars
  resources :tickets
  resources :events
  root "pages#home"
  get "/todo" => "pages#todo_index"
  get "filter" => "pages#filter"
  get "completed-tickets" => "tickets#completed"
  get "finalize" => "tickets#finalize_ticket"
  get "all" => "cars#all_cars"
  get "calendar" => "pages#calendar"
  get "admin" => "pages#admin"
  get "search" => "reports#set_filters"
end

app/models/ticket.rb
require "carrierwave"

class Ticket < ApplicationRecord
  belongs_to :car
  mount_uploaders :pictures, PictureUploader

  scope :category, -> (category) { where category: category }
  scope :location, -> (location) { where location: location }
  scope :completed, -> (completed) { where completed: completed }
  scope :car, -> (car) { where car_id: car }
  scope :created_after, -> (start_date) { where("created_at >= ?", start_date) }
  scope :created_before, -> (start_date) { where("created_at <= ?", start_date) }

  def notify
    @admin_list = YAML.load_file("config/administrators.yml")
    @twilio_number = ENV["TWILIO_NUMBER"]
    account_sid = ENV["TWILIO_SID"]
    @client = Twilio::REST::Client.new(account_sid, ENV["TWILIO_TOKEN"])
    reminder = "Ticket for #{self.car.name} has been completed."
    message = @client.api.account.messages.create(
      :from => @twilio_number,
      :to => @admin_list[0]["phone_number"],
      :body => reminder,
    )
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |ticket|
        csv << ticket.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @tickets = Ticket.all
    filtering_params.each do |key, value|
      @tickets = @tickets.public_send(key, value) if value.present?
    end

    respond_to do |format|
      format.html
      format.csv { send_data @tickets.to_csv }
      format.xls #{ render "results" }
    end
  end

  def show
    @ticket = Ticket.find_by(id: params[:id])
  end

  def finalize_ticket
    if params[:in_progress] == "true"
      ticket = Ticket.find_by(id: params[:id])
      ticket.in_progress = true
      ticket.save
    end
    @ticket = Ticket.find_by(id: params[:id])
    @parts = Part.order(:name)
  end

  def new
    @ticket = Ticket.new
    @car = Car.find(params[:car_id])
  end

  def edit
    @ticket = Ticket.find(params[:id])
  end

  def create
    @ticket = Ticket.new(ticket_params)

    @ticket.save
    redirect_to todo_path
  end

  def update
    @ticket = Ticket.find_by(id: params[:id])
    @ticket.update(ticket_params)
    @ticket.save
    if (@ticket.completed == true)
      @ticket.notify
    end
    if (params[:ticket][:part_used] && params[:ticket][:part_used].length > 1)
      part = Part.find(params[:ticket][:part_used])
      part.quantity -= 1
      part.save
    end
    redirect_to root_path
  end

  def completed
    if params[:filter]
      @completed = Ticket.where(completed: true, location: params[:filter])
    else
      @completed = Ticket.where(completed: true)
    end
  end

  def filtering_params
    params.permit(:car, :category, :location, :completed, :created_after, :created_before).to_h
  end

  helper_method :filtering_params

  private

  def ticket_params
    params.require(:ticket)
      .permit(:category, :note, {pictures: []}, :driveable, :mechanic, :car_id,
              :completed, :part_used, :time_spent, :location, :in_progress, :repair_under_warranty, :completed_on)
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_completed.html.erb
<div class="carContainer">
    <div class='ticketItem'>
        DESCRIPTION<br><br>
        <span class='wordBorder'> <%= @ticket.category %> </span>
    </div>
    <div class='ticketItem'>
        NOTES<br>
        <span class='ticketText'>
            <%= @ticket.note %>
        </span>
    </div>
    <div class='ticketItem'>
        LOCATION<br>
        <span class='ticketText'>
            <%= @ticket.location %>
        </span>
    </div>
    <div class='ticketItem'>
        <div class="imageContainer">
            PICTURES<br>
            <% if @ticket.pictures %>
            <div class="picContainer">
                <% @ticket.pictures.length.times do |x|%>
                    <%= link_to @ticket.pictures[x].url do %>
                        <%= image_tag @ticket.pictures[x].url, :class => "imgPreview" %>
                    <% end %>
                <% end %>
            </div>
            <% else %>
                No Picture Added
            <% end %>
        </div>
    </div>
    <div class='ticketItem'>
        COMPLETED BY<br>
        <span class='ticketText'>
            <%= @ticket.mechanic %> <br>
            <%= @ticket.completed_on.strftime('%v')   %>
        </span>
    </div>
        <div class='ticketItem'>
        UNDER WARRANTY<br>
        <span class='ticketText'>
            <%= @ticket.repair_under_warranty %> <br>
        </span>
    </div>

    <% if(@ticket.part_used != '' && @ticket.part_used)%>
        <div class='ticketItem'>
            PART USED<br>
            <span class='ticketText'>
                <%= Part.find(@ticket.part_used).name %>
            </span>
        </div>
    <% end %>

    <%= form_for @ticket, method: "patch" do |f| %>
    <%= f.hidden_field :category, value: @ticket.category %>
    <%= f.hidden_field :note, value: @ticket.note %>
    <%= f.hidden_field :pictures, value: @ticket.pictures %>
    <%= f.hidden_field :mechanic, value: @ticket.mechanic %>
    <%= f.hidden_field :car_id, value: @ticket.car_id %>
    <%= f.hidden_field :driveable, value: true %>

    <div class='submitTicketButton'>
        <%= f.hidden_field :completed, value: false %>
        <%= f.submit "REOPEN ISSUE", class: 'submitButton' %>
    </div>

    <% end %>
</div>

app/views/tickets/_editticket.html.erb
<div class='newTicketHeader'>
    <h2 class='header'> <%= @ticket.car.name %> </h2>
    <p class='gen'> <%= @ticket.car.generation %> </p>
</div>

<div class='ticketContainer'>
<%= form_with(model: ticket, local: true) do |f| %>
    <div class='ticketItem'>
        MAINTENANCE CATEGORY<br>
        <div class='select-style'>
            <%= f.select :category, ['Mechanical', 'Electrical', 'Body', 'Wrap', 'Other' ], {}, {required: 'true', autofocus: 'true' }%>
        </div>
    </div>
    <div class='ticketItem'>
        CAN THE CAR DRIVE?<br>
        <div class='select-style'>
            <%= f.select :driveable, [ ["Yes", true], ["No", false] ], {}, {required: 'true', autofocus: 'true' }%>
        </div>
    </div>
        <div class='ticketItem'>
        <div class="imageContainer">
            PICTURES<br>
            <% if @ticket.pictures %>
            <div class="picContainer">
                <% @ticket.pictures.length.times do |x|%>
                    <%= link_to @ticket.pictures[x].url do %>
                        <%= image_tag @ticket.pictures[x].url, :class => "imgPreview" %>
                    <% end %>
                <% end %>
            </div>
            <% else %>
                No Picture Added
            <% end %>
        </div>
    </div>
    <div class='ticketItem'>
        <div class="image-upload">
           ADD PICTURE<br><br>
            <div class="fileField">
            <%# <label for="file" class="input-label">
            <i class="fa fa-upload"></i> <span class="label-span">ADD PHOTOS</span>
            </label> %>
            <%= f.file_field :pictures, multiple: true, id: "file" %>
            </div>
        </div>


    </div>
        <div class='ticketItem'>
        LOCATION<br>
        <div class="select-style">
        <%= f.select :location, ['Coconut Grove', 'Coral Gables', 'Hallandale Beach', 'Key Biscayne', 'Mainland', 'Miami Lakes', 'South Beach', 'Other'], {}, {required: 'true', autofocus: 'true' } %> </div> <br>
    </div>

    <div class='ticketItem'>
        NOTES<br> <%= f.text_field :note %> <br>
    </div>

    <div class='ticketItem'>
        WARRANTY REPAIR?<br> <%= f.select :repair_under_warranty, [ ["Yes", true], ["No", false] ], {}, {required: 'true', autofocus: 'true' }%> <br>
    </div>

        <%= f.hidden_field :car_id, value: @ticket.car.id %>
        <%= f.hidden_field :completed, value: false %>
    <div class='submitTicketButton'>
        <%= f.submit "SAVE TICKET", class: 'submitButton' %>
    </div>
<% end %>
</div>

app/views/tickets/_notcompleted.html.erb
<div class="carContainer">
    <div class='ticketItem'>
        DESCRIPTION<br><br>
        <span class='wordBorder'> <%= @ticket.category %> </span>
    </div>
    <div class='ticketItem'>
        NOTES<br>
        <span class='ticketText'>
            <%= @ticket.note %>
        </span>
    </div>
        <div class='ticketItem'>
        LOCATION<br>
        <span class='ticketText'>
            <%= @ticket.location %>
        </span>
    </div>
        <div class='ticketItem'>
        UNDER WARRANTY<br>
        <span class='ticketText'>
            <%= @ticket.repair_under_warranty %> <br>
        </span>
    </div>
    <div class='ticketItem'>
        <div class="imageContainer">
            PICTURES<br>
            <% if @ticket.pictures %>
            <div class="picContainer">
                <% @ticket.pictures.length.times do |x|%>
                    <%= link_to @ticket.pictures[x].url do %>
                        <%= image_tag @ticket.pictures[x].url, :class => "imgPreview" %>
                    <% end %>
                <% end %>
            </div>
            <% else %>
                No Picture Added
            <% end %>
        </div>
    </div>

    <div class='submitTicketButton'>
        <%= link_to finalize_path(:id => @ticket.id,:start_time => Time.now, :in_progress => true ) do %>
        <span style="text-decoration: none;" class='submitButton'>START WORKING</span>
        <% end %>
    </div>

</div>

app/views/tickets/_ticketform.html.erb
<div class='newTicketHeader'>
    <h2 class='header'> <%= @car.name %> </h2>
    <p class='gen'> <%= @car.generation %> </p>
</div>

<div class='ticketContainer'>
<%= form_with(model: ticket, local: true) do |f| %>
    <div class='ticketItem'>
        MAINTENANCE CATEGORY<br>
        <div class='select-style'>
            <%= f.select :category, ['Mechanical', 'Electrical', 'Body', 'Wrap', 'Other' ], {}, {required: 'true', autofocus: 'true' }%>
        </div>
    </div>
    <div class='ticketItem'>
        CAN THE CAR DRIVE?<br>
        <div class='select-style'>
            <%= f.select :driveable, [ ["Yes", true], ["No", false] ], {}, {required: 'true', autofocus: 'true' }%>
        </div>
    </div>
    <div class='ticketItem'>
        <div class="image-upload">
           ADD PICTURE<br><br>
            <div class="fileField">
            <%# <label for="file" class="input-label">
            <i class="fa fa-upload"></i> <span class="label-span">ADD PHOTOS</span>
            </label> %>
            <%= f.file_field :pictures, multiple: true, id: "file" %>
            </div>
        </div>


    </div>
        <div class='ticketItem'>
        LOCATION<br>
        <div class="select-style">
        <%= f.select :location, ['Coconut Grove', 'Coral Gables', 'Hallandale Beach', 'Key Biscayne', 'Mainland', 'Miami Lakes', 'South Beach', 'Other'], {}, {required: 'true', autofocus: 'true' } %> </div> <br>
    </div>

    <div class='ticketItem'>
        NOTES<br> <%= f.text_field :note %> <br>
    </div>

    <div class='ticketItem'>
        WARRANTY REPAIR?<br> <%= f.select :repair_under_warranty, [ ["Yes", true], ["No", false] ], {}, {required: 'true', autofocus: 'true' }%> <br>
    </div>

        <%= f.hidden_field :car_id, value: params[:car_id] %>
        <%= f.hidden_field :completed, value: false %>
    <div class='submitTicketButton'>
        <%= f.submit "CREATE TICKET", class: 'submitButton' %>
    </div>
<% end %>
</div>

app/views/tickets/completed.html.erb
<%= render partial: 'layouts/navbar', locals: {title: "COMPLETED"} %>


<%= form_for "", url: completed_tickets_path, method: :get do |f| %>
	<div id="filter-header"> ZONE </div>
	<div class="filter-style">
	<%= f.select :filter, ['Coconut Grove', 'Coral Gables', 'Hallandale Beach', 'Key Biscayne', 'Mainland', 'Miami Lakes', 'South Beach', 'Other'], {
		:include_blank => true, id: "filter" } , { onchange: 'this.form.submit();', prompt: 'Select Person' } %>
	</div>
<% end %>

<div class='priorityBox'>
    <div class='priorityBoxTitle'> COMPLETED TICKETS </div>
    <% @completed.each do |item| %>
        <div class='priorityTickets'>
             <%= link_to ticket_path(:id => item.id) do %>
                <div class='ticketLink'>
                    <div class="leftDiv"><%= item.car.name %></div>
                    <div class="centerDiv"><%= item.category %></div>
                    <div class="rightDiv"><%= item.car.generation %></div>
                </div>
            <% end %>
        </div>
    <% end %>
</div>

app/views/tickets/edit.html.erb
<%= render partial: 'layouts/navbar', locals: {title: "EDIT TICKET"} %>

<%= render 'editticket', ticket: @ticket %>

app/views/tickets/finalize_ticket.html.erb
<%= render partial: 'layouts/navbar', locals: {title: "CLOSE TICKET"} %>

<h2 class="header"><%= @ticket.car.name %></h1>

<% if notice %>
    <div> <%= notice %> </div>
<% end %>

<div class="carContainer">
    <div class='ticketItem'>
        DESCRIPTION<br><br>   
       <span class='wordBorder'> <%= @ticket.category %> </span>
    </div>

    <div class='ticketItem'>
        NOTES<br><br>
        <%= @ticket.note %>
    </div>

    <div class='ticketItem'>
        <div class="imageContainer">
            PICTURES<br>
            <% if @ticket.pictures %>
            <div class="picContainer">
                <% @ticket.pictures.length.times do |x|%>
                    <%= image_tag @ticket.pictures[x].url, :class => "imgPreview" %>
                <% end %>
            </div>
            <% else %>
                No Picture Added
            <% end %>
        </div>
    </div>


    <%= form_for @ticket, method: "patch" do |f| %>
        <%= f.hidden_field :category, value: @ticket.category %>
        <%= f.hidden_field :note, value: @ticket.note %>
        <%= f.hidden_field :pictures, value: @ticket.pictures %>

    <div class='ticketItem'>
        PART USED<br>
        <div class='select-style'>
            <%= f.select(:part_used, @parts.map{ |x| [x.name, x.id] if x.quantity != nil && x.quantity > 0  }, {:include_blank => true}) %>
        </div>
    </div>

    <div class='ticketItem'>
        COMPLETED BY<br> <%= f.text_field :mechanic %>
    </div>

    <div class='ticketItem'>
        FINAL RESOLUTION<br> <%= f.text_field :final_resolution %>
    </div>


        <%# f.hidden_field :time_spent, value: distance_of_time_in_words(Time.now, params[:start_time])%>
        <%= f.hidden_field :car_id, value: @ticket.car_id %>
        <%= f.hidden_field :driveable, value: true %>
        <%= f.hidden_field :completed_on, value: Date.today %>

            <div class="submitTicketButton">

                <%= f.hidden_field :completed, value: true %>
                <%= f.submit "JOB COMPLETE", class: 'submitButton final' %>
                <% end %>



                <%= form_for @ticket, method: "patch" do |d| %>
                <%= d.hidden_field :in_progress, value: false %>
                <%= d.submit "PAUSE JOB", class: 'submitButton final' %>
                <% end %>
            </div>


</div>

app/views/tickets/index.html.erb
<%= render partial: 'layouts/navbar', locals: {title: "REPORTS"} %>

<h3 classs='header'> RESULTS </h3>
<div class='priorityBox'>
    <div class='priorityBoxTitle'> TICKETS </div>
    <% @tickets.each do |item| %>
        <div class='priorityTickets'>
             <% if(item.in_progress) == true %>
             <%= link_to finalize_path(:id => item.id) do %>
                <div class='ticketLink green'>
                    <div class="leftDiv"><%= item.car.name %></div>
                    <div class="centerDiv"><%= item.category %></div>
                    <div class="rightDiv"><%= item.car.generation %></div>
                </div>
                <% end %>
                <% else %>
             <%= link_to ticket_path(:id => item.id) do %>
                <div class='ticketLink'>
                    <div class="leftDiv"><%= item.car.name %></div>
                    <div class="centerDiv"><%= item.category %></div>
                    <div class="rightDiv"><%= item.car.generation %></div>
                </div>
            <% end %>
            <% end %>
        </div>
    <% end %>
</div>

<%= link_to "Download Excel File", tickets_path(filtering_params.merge(format: :xls)) %>

app/views/tickets/index.xls.erb
<table border='1'>
<tr>
  <th> Name </th>
  <th> Category </th>
  <th> Location </th>
  <th> Created On </th>
  <th> Note </th>
  <th> Completed </th>
  <th> Mechanic </th>
  <th> Part used </th>
  <th> Final Resolution </th>
</tr>
<% @tickets.each do |ticket| %>
  <tr>
    <td> <%= ticket.car.name %> </td>
    <td> <%= ticket.category %> </td>
    <td> <%= ticket.location %> </td>
    <td> <%= ticket.created_at %> </td>
    <td> <%= ticket.note %> </td>
    <td> <%= ticket.completed %> </td>
    <td> <%= ticket.mechanic %> </td>
    <td> <%= ticket.part_used %> </td>
    <td> <%= ticket.final_resolution %> </td>
  </tr>
<% end %>

</table>

app/views/tickets/new.html.erb
<%= render partial: 'layouts/navbar', locals: {title: "ADD ISSUE"} %>


<%= render 'ticketform', ticket: @ticket %>

app/views/tickets/show.html.erb
<%= render partial: 'layouts/navbar', locals: {title: "PRIORITY TO-DO LIST"} %>


<h2 class="header"><%= @ticket.car.name %></h1>
<div style='text-align:center;'>
Created on: <%= @ticket.created_at.to_formatted_s(:long)  %>
</div>

<% if @ticket.completed == false %>
    <%= render 'notcompleted' %>
<% elsif @ticket.completed == true %>
    <%= render 'completed' %>
<% end %>


<%= link_to 'EDIT TICKET', edit_ticket_path(:ticket => @ticket, @ticket.car => @car ) %>