config/routes.rb
Rails.application.routes.draw do
  resources :parts
  devise_for :users, controllers: {registrations: "registrations"}
  resources :cars
  resources :tickets
  resources :events
  root "pages#home"
  get "/todo" => "pages#todo_index"
  get "filter" => "pages#filter"
  get "completed-tickets" => "tickets#completed"
  get "finalize" => "tickets#finalize_ticket"
  get "all" => "cars#all_cars"
  get "calendar" => "pages#calendar"
  get "admin" => "pages#admin"
  get "search" => "reports#set_filters"
end

app/models/car.rb
class Car < ApplicationRecord
    has_many :tickets
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      redirect_to root_path
    end
  end

  def show
    @car = Car.find(params[:id])
  end

  def all_cars
    @cars = Car.all
  end

  private

  def car_params
    params.require(:car).permit(:name, :generation)
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<div class="formContainer">
  <%= form_with(model: car, local: true) do |form| %>

    <div class="ticketItem">
      NAME
      <%= form.text_field :name %>
    </div>

    <div class="ticketItem">
      GENERATION
      <%= form.text_field :generation %>
    </div>

    <div class="doneButton">
      <%= form.submit "DONE", id: "done" %>
    </div>
  <% end %>
</div>

app/views/cars/all_cars.html.erb
<%= render partial: 'layouts/navbar', locals: {title: "CARS"} %>


<h2 class="header">ALL CARS</h2>

<div class='carContainer'>
        <% @cars.each do |car| %>          
            <%= link_to car_path(:id => car.id) do %>
                <div class='carLink'> 
                    <p class="alignleft"> <%= car.name %> </p>
                    <p class="alignright"> <%= car.generation %> </p>
                </div>
            <% end %>
        <% end %>
</div>

app/views/cars/index.html.erb
<%= render partial: 'layouts/navbar', locals: {title: "ADD ISSUE"} %>

<h2 class="header">CHOOSE CAR</h2>


<div class='carContainer'>
        <% @cars.each do |car| %>          
            <%= link_to new_ticket_path(:car_id => car.id) do %>
                <div class='carLink'> 
                    <p class="alignleft"> <%= car.name %> </p>
                    <p class="alignright"> <%= car.generation %> </p>
                </div>
            <% end %>
        <% end %>
</div>

app/views/cars/new.html.erb
<%= render partial: 'layouts/navbar', locals: {title: "ADD CAR"} %>

<%= render 'form', car: @car %>

app/views/cars/show.html.erb
<%= render partial: 'layouts/navbar', locals: {title: @car.name} %>

<h2 class="header"> OPEN ISSUES </h2>


<div class='carContainer'>
        <% @car.tickets.each do |ticket| %>
            <%= link_to ticket_path(:id => ticket.id) do %>
                <div class='carLink'>
                    <p class="alignleft"> <%= ticket.category %> </p>
                    <p class="alignright"> 
                        <% if ticket.completed == true %>
                            COMPLETED
                            <% else %>
                            NOT COMPLETED
                        <% end %>
                    </p>
                </div>
            <% end %>
        <% end %>
</div>